
import React from 'react';
import { Gavel, UserCheck, CreditCard, PenTool } from 'lucide-react';

const TermsAndConditions: React.FC = () => {
  return (
    <div className="pt-32 pb-16 px-4 max-w-4xl mx-auto min-h-screen">
      <h1 className="text-5xl font-extrabold mb-8">Terms and Conditions</h1>
      
      <div className="space-y-12 text-slate-300 leading-relaxed">
        <section className="space-y-4">
          <div className="flex items-center gap-3 text-indigo-400">
            <UserCheck size={24} />
            <h2 className="text-2xl font-bold text-white">User Responsibilities</h2>
          </div>
          <p>
            By using Promptifie, you represent and warrant that you have the legal right to upload any images you submit to our service. You must not upload content that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Is illegal, harmful, threatening, or defamatory.</li>
            <li>Infringes upon any third-party intellectual property or privacy rights.</li>
            <li>Contains viruses or malicious code.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-indigo-400">
            <CreditCard size={24} />
            <h2 className="text-2xl font-bold text-white">Subscription Terms</h2>
          </div>
          <p>
            Promptifie offers both free and paid subscription tiers. Paid tiers are billed on a recurring basis (monthly or annually). You may cancel your subscription at any time through your dashboard; however, access to premium features will continue until the end of the current billing cycle.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-indigo-400">
            <PenTool size={24} />
            <h2 className="text-2xl font-bold text-white">Intellectual Property Rights</h2>
          </div>
          <p>
            You retain all rights to the prompts generated by Promptifie based on your uploaded content. Promptifie retains all rights, title, and interest in and to the platform, including its proprietary algorithms, design, and trademarks.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-3 text-indigo-400">
            <Gavel size={24} />
            <h2 className="text-2xl font-bold text-white">Limitations of Liability</h2>
          </div>
          <p>
            Promptifie provides its services "as is" and makes no warranties regarding the specific results or accuracy of generated prompts. We shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsAndConditions;
